<?php

/**
 * Returns the import map for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "preload" set to true for any modules that are loaded on the initial
 *     page load to help the browser download them earlier.
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => 'app.js',
        'preload' => true,
    ],
    '@popperjs/core' => [
        'downloaded_to' => 'vendor/@popperjs/core.js',
        'url' => 'https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/+esm',
    ],
    'bootstrap' => [
        'downloaded_to' => 'vendor/bootstrap.js',
        'url' => 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/+esm',
    ],
    'owlcarousel' => [
        'url' => 'https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js',
    ],
];
