name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main

env:
  fail-fast: true
  PHPUNIT_FLAGS: "-v"
  SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"
  SYMFONY_DEPRECATIONS_HELPER: 7

#permissions:
#  contents: read

jobs:
  test:
    name: "${{ matrix.operating-system }} / PHP ${{ matrix.php-version }}"
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: false

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['8.2']
#        include:
#          - operating-system: 'macos-latest'
#            php-version: '8.2'
#          - operating-system: 'windows-latest'
#            php-version: '8.2'
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 'Password123!'
        ports:
          - 3306:3306
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker containers
        run: |
          docker-compose -f docker-compose.yml up --build -d
          sleep 10

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: "intl, mbstring, pdo_sqlite"
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: "Add PHPUnit matcher"
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: "Set composer cache directory"
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: "Cache composer"
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

      - name: "Install dependencies"
        run: composer install --no-interaction --no-progress

      - name: "Install PHPUnit"
        run: vendor/bin/simple-phpunit install

      - name: "PHPUnit version"
        run: vendor/bin/simple-phpunit --version

      - name: "Run tests"
        run: vendor/bin/simple-phpunit ${{ env.PHPUNIT_FLAGS }}